version: "3.9"

services:

  backend:
    build: .
    container_name: bikelo_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      - postgres
    networks:
      - bikelo-network

  postgres:
    image: postgres:16
    container_name: bikelo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikelo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bikelo-network

volumes:
  postgres_data:
  uploads:

networks:
  bikelo-network: