services:

  postgres:
    image: postgres:16
    container_name: bikelo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikelo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bikelo-network
    restart: always

  backend:
    build: .
    container_name: bikelo_backend
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - uploads:/app/uploads
    networks:
      - bikelo-network
    restart: always

volumes:
  postgres_data:
  uploads:

networks:
  bikelo-network:
    driver: bridge