version: "3.9"

services:

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bikelo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bikelo-network

  backend:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - uploads:/app/uploads
    expose:
      - "8000"
    networks:
      - bikelo-network

  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - bikelo-network

volumes:
  postgres_data:
  uploads:

networks:
  bikelo-network:
