[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "psycopg2-binary>=2.9.9",
    "fastapi>=0.135.1",
    "uvicorn[standard]>=0.30.0",
    "sqlalchemy>=2.0.48",
    "pydantic[email]>=2.0",
    "pyjwt>=2.8",
    "bcrypt>=4.0.0",
    "slowapi>=0.1.9",
    "python-multipart>=0.0.22",
    "requests>=2.32.5",
]
